### ISSUE TITLE
Code for the fine-tuning process

### ISSUE THREAD

**Issue by star9988rr** [salesforce/ULIP#12]
Thanks for your amazing work! Can you provide the code for fine-tuning the models on modelnet40 and scanobjectnn? Or what codebase do you use?

**Comment by Tycho-Xue** [comment]
thanks for your interest in our work. We didn't integrate the fine-tune code into ULIP by default. Our process is like: 1. we pre-train the backbone using ULIP using a specific backbone, then take the backbone back to its original repo, then initialize with the pre-trained weights, then finetune, we don't change the backbone architecture, only tune the hyper parameters like Lr, and we found that since we are not training from scratch anymore, so the default hyper parameters might not be optimal anymore, we will release the fine-tune checkpoints with logs and the hyper parameters we used soon.
the repo we used are:
https://github.com/ma-xu/pointMLP-pytorch
https://github.com/lulutang0608/Point-BERT
https://github.com/guochengqian/PointNeXt
