### ISSUE TITLE
Question about ScanObjectNN

### ISSUE THREAD

**Issue by auniquesun** [salesforce/ULIP#20]
Hi, @Tycho-Xue , thanks for sharing the paper and code. 

I notice you reported the finetuned results on ScanObjectNN in Table 1. Since there are 3 splits of this dataset, I wonder which split do you test ULIP on? 

By the way, can you share the pytorch dataset definition of ScanObjectNN, or list some referenced implementations of this dataset, I just want to reproduce the results and try new ideas.

Thanks.

**Comment by Colin97** [comment]
Also, would like to know do you evaluate the results on train & test sets or test sets only.

**Comment by auniquesun** [comment]
@Colin97 We have different contexts.

Here I mean the 3 splits of ScanObjectNN are _OBJ_ONLY, OBJ_BJ, Hardest_ modes.

**Comment by Tycho-Xue** [comment]
@auniquesun, we evaluate on the scanobjectnn hardest modes, because:1. it's the most challenging one. 2. not all the backbones we used reported results on the other two modes so it's hard to compare for other modes.
I will try to find some time recently to release the fine-tuned checkpoints with the logs and hyperparameters, also the scanobjectnn dataset definitions; if you are in a hurry, you can follow pointmlp/pointbert/pointnext on how they implement the scanobjectnn datasets, it's kind of similar and standard, just refer to the 3d backbone you plan to use.

Thanks.

**Comment by Tycho-Xue** [comment]
@auniquesun, if you are talking about the zero-shot classification instead of fine-tuning, kindly check this out https://github.com/salesforce/ULIP/issues/21#issuecomment-1515545698
